# Generated by Django 5.2 on 2025-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='verification_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
