# Generated by Django 5.2 on 2025-04-14 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_code_expires_at_author_verification_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['code_expires_at'], name='author_auth_code_ex_8a45b2_idx'),
        ),
    ]
